### ISSUE TITLE
json output option for rosa create admin 

### ISSUE THREAD

**Issue by rajmechi** [openshift/rosa#583] opened 2022-01-27 16:37 UTC
json output option for rosa create admin. currently it's giving text output in cli 1.1.7

**Comment by jbpratt** [comment] 2022-03-02 09:51
duplicate of https://github.com/openshift/rosa/issues/452

**Comment by jbpratt** [comment] 2022-03-07 10:55
still a relevant issue
```
❯ rosa create admin -c test -o json
Error: unknown shorthand flag: 'o' in -o
Usage:
  rosa create admin [flags]

Examples:
  # Create an admin user to login to the cluster
  rosa create admin -c mycluster -p MasterKey123

Flags:
  -c, --cluster string    Name or ID of the cluster.
  -h, --help              help for admin
  -p, --password string   Choice of password for admin user.

Global Flags:
      --debug            Enable debug mode.
      --profile string   Use a specific AWS profile from your credential file.
      --region string    Use a specific AWS region, overriding the AWS_REGION environment variable.
  -y, --yes              Automatically answer yes to confirm operation.

Failed to execute root command: unknown shorthand flag: 'o' in -o
```

**Closed** 2022-08-04 13:32 UTC
Labels: lifecycle/rotten
